repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    #- id: end-of-file-fixer
  - repo: local
    hooks:
    - id: jupytext
      name: jupytext
      language: python
      files: '.*\.ipynb$'
      exclude: '^venv/.*'
      entry: jupytext --to py:percent
